# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NLQQuery',
            fields=[
                ('id', models.BigAutoField(db_column='nlq_query_id', primary_key=True, serialize=False)),
                ('raw_query', models.TextField()),
                ('detected_intent', models.CharField(blank=True, max_length=150)),
                ('extracted_filters', models.JSONField(blank=True, default=dict)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nlq_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nlq_query',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user'], name='nlq_query_user_id_8c4ded_idx'), models.Index(fields=['detected_intent'], name='nlq_query_detecte_fc940a_idx'), models.Index(fields=['created_at'], name='nlq_query_created_e2c444_idx')],
            },
        ),
    ]
