# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOPHLEmailParse',
            fields=[
                ('id', models.BigAutoField(db_column='email_parse_id', primary_key=True, serialize=False)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('case_number_detected', models.CharField(blank=True, max_length=80)),
                ('report_type', models.CharField(blank=True, max_length=150)),
                ('deadline_detected', models.DateField(blank=True, null=True)),
                ('required_action', models.TextField(blank=True)),
                ('attachments_metadata', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('failed', 'Failed')], default='unmatched', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_case', models.ForeignKey(blank=True, db_column='matched_case_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipophl_email_parses', to='cases.case')),
            ],
            options={
                'db_table': 'ipophl_email_parse',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sender'], name='ipophl_emai_sender_0c4964_idx'), models.Index(fields=['case_number_detected'], name='ipophl_emai_case_nu_ae5742_idx'), models.Index(fields=['report_type'], name='ipophl_emai_report__528ce4_idx'), models.Index(fields=['deadline_detected'], name='ipophl_emai_deadlin_da6139_idx'), models.Index(fields=['status'], name='ipophl_emai_status_148eac_idx')],
            },
        ),
    ]