# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(db_column='inquiry_id', primary_key=True, serialize=False)),
                ('inquiry_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('popularity_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('answered', 'Answered'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, db_column='listing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='marketplace.marketlisting')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inquiry',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['inquiry_code'], name='inquiry_inquiry_7522f9_idx'), models.Index(fields=['user'], name='inquiry_user_id_090206_idx'), models.Index(fields=['listing'], name='inquiry_listing_49a296_idx'), models.Index(fields=['category'], name='inquiry_categor_9f78e9_idx'), models.Index(fields=['status'], name='inquiry_status_1d105d_idx'), models.Index(fields=['popularity_count'], name='inquiry_popular_1ca465_idx')],
            },
        ),
    ]
