# Generated by Django 5.2.1 on 2026-06-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inquiry',
            name='inquiry_inquiry_7522f9_idx',
        ),
    ]
