# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('cases', '0001_initial'),
        ('security_keys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAssessment',
            fields=[
                ('id', models.BigAutoField(db_column='assessment_id', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_type', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('paid', 'Paid'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.PROTECT, related_name='fee_assessments', to='applications.ipapplication')),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='fee_assessments', to='cases.case')),
                ('evaluator', models.ForeignKey(blank=True, db_column='evaluator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_fee_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fee_assessment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(db_column='payment_id', primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=80)),
                ('receipt_no', models.CharField(blank=True, max_length=100)),
                ('encrypted_receipt_file', models.FileField(upload_to='encrypted/receipts/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('nonce', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=64)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.feeassessment')),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cases.case')),
                ('encryption_key', models.ForeignKey(db_column='encryption_key_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='security_keys.encryptionkey')),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='feeassessment',
            index=models.Index(fields=['case'], name='fee_assessm_case_id_477045_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassessment',
            index=models.Index(fields=['application'], name='fee_assessm_applica_7c73dc_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassessment',
            index=models.Index(fields=['evaluator'], name='fee_assessm_evaluat_7b8d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassessment',
            index=models.Index(fields=['status'], name='fee_assessm_status_cd983c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['assessment'], name='payment_assessm_91b40e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['case'], name='payment_case_id_1237eb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['applicant'], name='payment_applica_21c5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='payment_payment_285a08_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payment_payment_904250_idx'),
        ),
    ]
