# Generated by Django 5.2.1 on 2026-06-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_activitytimeline_case_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeassessment',
            name='case',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.PROTECT, related_name='fee_assessments', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='case',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cases.case'),
        ),
    ]
