# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPApplication',
            fields=[
                ('id', models.BigAutoField(db_column='application_id', primary_key=True, serialize=False)),
                ('application_code', models.CharField(editable=False, max_length=40, unique=True)),
                ('ip_type', models.CharField(choices=[('patent', 'Patent'), ('utility_model', 'Utility Model'), ('industrial_design', 'Industrial Design'), ('trademark', 'Trademark'), ('copyright', 'Copyright')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('claims', models.TextField(blank=True)),
                ('technical_explanation', models.TextField(blank=True)),
                ('novelty_explanation', models.TextField(blank=True)),
                ('supporting_details', models.TextField(blank=True)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('completeness_score', models.PositiveSmallIntegerField(default=0)),
                ('language_validation_status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('failed', 'Failed')], default='valid', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, related_name='ip_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ip_application',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationChecklist',
            fields=[
                ('id', models.BigAutoField(db_column='checklist_id', primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('missing', 'Missing'), ('needs_review', 'Needs Review'), ('optional', 'Optional')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='applications.ipapplication')),
            ],
            options={
                'db_table': 'application_checklist',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['application_code'], name='ip_applicat_applica_77989d_idx'),
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['applicant'], name='ip_applicat_applica_e9ba39_idx'),
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['ip_type'], name='ip_applicat_ip_type_e35c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['status'], name='ip_applicat_status_fdf317_idx'),
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['submitted_at'], name='ip_applicat_submitt_d7b8be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationchecklist',
            unique_together={('application', 'item_name')},
        ),
    ]
