# Generated by Django 4.2.30 on 2026-04-16 08:52

import core.utils.file_validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_type', models.CharField(choices=[('Patent', 'Patent'), ('Trademark', 'Trademark'), ('Copyright', 'Copyright'), ('Collaboration', 'Collaboration')], max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Deficient', 'Deficient'), ('Certified', 'Certified')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=core.utils.file_validators.generate_upload_path, validators=[core.utils.file_validators.validate_file_extension, core.utils.file_validators.validate_file_size])),
                ('document_type', models.CharField(choices=[('Blueprint', 'Blueprint'), ('Affidavit', 'Affidavit'), ('Receipt', 'Receipt'), ('Specification', 'Specification'), ('Drawing', 'Drawing'), ('Support', 'Supporting Document'), ('Manuscript', 'Manuscript'), ('Declaration', 'Declaration'), ('MarkImage', 'Mark Image'), ('Other', 'Other')], default='Other', max_length=20)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.ipapplication')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CoInventor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinventors', to='applications.ipapplication')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['status'], name='application_status_0b3373_idx'),
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['created_by'], name='application_created_1afb66_idx'),
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['assigned_evaluator'], name='application_assigne_23043e_idx'),
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['ip_type'], name='application_ip_type_39a9d9_idx'),
        ),
    ]
