# Generated by Django 4.2.30 on 2026-04-19 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipapplication',
            name='isbn',
            field=models.CharField(blank=True, default='', help_text='International Standard Book Number (Copyright: Books).', max_length=20),
        ),
        migrations.AddField(
            model_name='ipapplication',
            name='ismn',
            field=models.CharField(blank=True, default='', help_text='International Standard Music Number (Copyright: Music).', max_length=20),
        ),
        migrations.AddField(
            model_name='ipapplication',
            name='issn',
            field=models.CharField(blank=True, default='', help_text='International Standard Serial Number (Copyright: Periodicals).', max_length=20),
        ),
        migrations.AddField(
            model_name='ipapplication',
            name='marketplace_consent',
            field=models.BooleanField(default=False, help_text="Applicant's consent to display this IP in the public marketplace."),
        ),
        migrations.AddField(
            model_name='ipapplication',
            name='stage',
            field=models.CharField(choices=[('IPTTO', 'IPTTO Evaluation'), ('IPOPHL', 'IPOPHL Processing')], default='IPTTO', help_text='Current processing stage: IPTTO evaluation or IPOPHL submission.', max_length=10),
        ),
        migrations.AddField(
            model_name='ipdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the evaluator applied their review stamp.', null=True),
        ),
        migrations.AddField(
            model_name='ipdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Evaluator who stamped this document as reviewed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ipapplication',
            name='ip_type',
            field=models.CharField(choices=[('Patent', 'Patent'), ('Trademark', 'Trademark'), ('Copyright', 'Copyright'), ('Utility Model', 'Utility Model'), ('Industrial Design', 'Industrial Design')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ipapplication',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Deficient', 'Deficient'), ('Certified', 'Certified'), ('Forwarded to IPOPHL', 'Forwarded to IPOPHL'), ('IPOPHL Under Review', 'IPOPHL Under Review'), ('IPOPHL Deficient', 'IPOPHL Deficient'), ('Registered', 'Registered')], default='Draft', max_length=30),
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['stage'], name='application_stage_528283_idx'),
        ),
    ]
