# Generated by Django 5.2.1 on 2026-06-08 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ipapplication',
            name='ip_applicat_applica_77989d_idx',
        ),
        migrations.AlterField(
            model_name='ipapplication',
            name='applicant',
            field=models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.PROTECT, related_name='ip_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
