# Generated by Django 4.2.30 on 2026-05-01 14:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def populate_transaction_codes(apps, schema_editor):
    IPApplication = apps.get_model('applications', 'IPApplication')
    for application in IPApplication.objects.filter(
        models.Q(transaction_code__isnull=True) | models.Q(transaction_code='')
    ):
        created = application.created_at
        date_part = created.strftime('%Y%m%d') if created else '00000000'
        application.transaction_code = f"TCB-{date_part}-{uuid.uuid4().hex[:8].upper()}"
        application.save(update_fields=['transaction_code'])


def seed_ip_requirements(apps, schema_editor):
    IPRequirement = apps.get_model('applications', 'IPRequirement')
    requirements = [
        ('Patent', 'Patent Request Form', 'Primary IPOPHL request form for patent filing.', 'form', 'Checklist', True, 10),
        ('Patent', 'Supplementary Sheet', 'Additional inventor/application details when required.', 'form', 'Checklist', True, 20),
        ('Patent', 'Technical Specification, Claims, and Abstract', 'Detailed invention disclosure, claims, and abstract for evaluation.', 'supporting_document', 'Specification', True, 30),
        ('Patent', 'Blueprints or Technical Drawings', 'High-resolution drawings or diagrams of the invention.', 'supporting_document', 'Blueprint', True, 40),
        ('Patent', 'Petition for Cancellation', 'Optional petition form for cancellation-related patent services.', 'legal', 'Checklist', False, 50),
        ('Patent', 'Proof of Payment Receipt', 'Digital copy of bank or university cashier receipt.', 'payment', 'Receipt', True, 60),
        ('Utility Model', 'Utility Model Registration Form', 'Primary registration form for utility model filing.', 'form', 'Checklist', True, 10),
        ('Utility Model', 'Technical Description and Claims', 'Utility model description, claims, and required technical details.', 'supporting_document', 'Specification', True, 20),
        ('Utility Model', 'Drawings or Photos', 'Visual materials that explain the model.', 'supporting_document', 'Drawing', True, 30),
        ('Utility Model', 'Petition for Cancellation', 'Optional petition form for cancellation-related utility model services.', 'legal', 'Checklist', False, 40),
        ('Utility Model', 'Proof of Payment Receipt', 'Digital copy of bank or university cashier receipt.', 'payment', 'Receipt', True, 50),
        ('Industrial Design', 'Industrial Design Registration Form', 'Primary registration form for industrial design filing.', 'form', 'Checklist', True, 10),
        ('Industrial Design', 'Design Description', 'Description of the ornamental or aesthetic aspects of the article.', 'supporting_document', 'Specification', True, 20),
        ('Industrial Design', '3D Drawings or Product Photos', 'Photographs or drawings showing the appearance of the design.', 'supporting_document', 'Drawing', True, 30),
        ('Industrial Design', 'Petition for Cancellation', 'Optional petition form for cancellation-related industrial design services.', 'legal', 'Checklist', False, 40),
        ('Industrial Design', 'Proof of Payment Receipt', 'Digital copy of bank or university cashier receipt.', 'payment', 'Receipt', True, 50),
        ('Copyright', 'Copyright Registration Form', 'Primary copyright registration form.', 'form', 'Checklist', True, 10),
        ('Copyright', 'Supplementary Form', 'Additional copyright filing details when required.', 'form', 'Checklist', True, 20),
        ('Copyright', 'Manuscript or Creative Work', 'Copy of the work being protected, such as text, music, software, or artwork.', 'supporting_document', 'Manuscript', True, 30),
        ('Copyright', 'ISBN, ISSN, or ISMN Details', 'National Library identifier details when applicable.', 'supporting_document', 'Declaration', False, 40),
        ('Copyright', 'Other Services Form', 'Optional form for related copyright services.', 'form', 'Checklist', False, 50),
        ('Copyright', 'Proof of Payment Receipt', 'Digital copy of bank or university cashier receipt.', 'payment', 'Receipt', True, 60),
    ]
    for ip_type, title, description, category, document_type, is_required, sort_order in requirements:
        IPRequirement.objects.get_or_create(
            ip_type=ip_type,
            title=title,
            defaults={
                'description': description,
                'category': category,
                'expected_document_type': document_type,
                'is_required': is_required,
                'sort_order': sort_order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_ipapplication_isbn_ipapplication_ismn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_type', models.CharField(choices=[('Patent', 'Patent'), ('Copyright', 'Copyright'), ('Utility Model', 'Utility Model'), ('Industrial Design', 'Industrial Design')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('form', 'Form'), ('supporting_document', 'Supporting Document'), ('payment', 'Payment'), ('legal', 'Legal'), ('guideline', 'Guideline')], default='form', max_length=30)),
                ('expected_document_type', models.CharField(blank=True, choices=[('Blueprint', 'Blueprint'), ('Affidavit', 'Affidavit'), ('Receipt', 'Receipt'), ('Specification', 'Specification'), ('Drawing', 'Drawing'), ('Support', 'Supporting Document'), ('Manuscript', 'Manuscript'), ('Declaration', 'Declaration'), ('Checklist', 'Checklist/Form'), ('Other', 'Other')], default='', help_text='Optional document type expected when this requirement is uploaded.', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ip_type', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ipapplication',
            name='archive_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ipapplication',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipapplication',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipapplication',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived records remain retained but are hidden from active queues.'),
        ),
        migrations.AddField(
            model_name='ipapplication',
            name='transaction_code',
            field=models.CharField(blank=True, editable=False, help_text='Applicant-facing case code used for searching and tracking.', max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(populate_transaction_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ipapplication',
            name='transaction_code',
            field=models.CharField(blank=True, editable=False, help_text='Applicant-facing case code used for searching and tracking.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ipapplication',
            name='ip_type',
            field=models.CharField(choices=[('Patent', 'Patent'), ('Copyright', 'Copyright'), ('Utility Model', 'Utility Model'), ('Industrial Design', 'Industrial Design')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ipapplication',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Evaluation', 'Under Evaluation'), ('Under Review', 'Under Review (legacy)'), ('Deficient', 'Deficient'), ('Certified', 'Certified'), ('Forwarded to IPOPHL', 'Forwarded to IPOPHL'), ('IPOPHL Under Review', 'IPOPHL Under Review'), ('IPOPHL Deficient', 'IPOPHL Deficient'), ('Registered', 'Registered')], default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='ipdocument',
            name='document_type',
            field=models.CharField(choices=[('Blueprint', 'Blueprint'), ('Affidavit', 'Affidavit'), ('Receipt', 'Receipt'), ('Specification', 'Specification'), ('Drawing', 'Drawing'), ('Support', 'Supporting Document'), ('Manuscript', 'Manuscript'), ('Declaration', 'Declaration'), ('Checklist', 'Checklist/Form'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['transaction_code'], name='application_transac_5cfcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='ipapplication',
            index=models.Index(fields=['is_archived', '-created_at'], name='application_is_arch_6bfed4_idx'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applications.ipapplication'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='receipt_document',
            field=models.ForeignKey(blank=True, limit_choices_to={'document_type': 'Receipt'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='applications.ipdocument'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='iprequirement',
            index=models.Index(fields=['ip_type', 'is_active'], name='application_ip_type_e6868b_idx'),
        ),
        migrations.AddIndex(
            model_name='iprequirement',
            index=models.Index(fields=['category'], name='application_categor_49a795_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['application', '-created_at'], name='application_applica_6fd559_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['status'], name='application_status_668a58_idx'),
        ),
        migrations.RunPython(seed_ip_requirements, migrations.RunPython.noop),
    ]
