# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(db_column='case_id', primary_key=True, serialize=False)),
                ('case_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('evaluated', 'Evaluated'), ('on_going', 'On Going'), ('certified', 'Certified'), ('archived', 'Archived')], default='pending', max_length=30)),
                ('priority_score', models.PositiveIntegerField(default=0)),
                ('priority_label', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('sla_stage', models.CharField(blank=True, max_length=100)),
                ('sla_due_date', models.DateTimeField(blank=True, null=True)),
                ('evaluation_summary', models.TextField(blank=True)),
                ('evaluator_recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.PROTECT, related_name='applicant_cases', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(db_column='application_id', on_delete=django.db.models.deletion.PROTECT, related_name='case', to='applications.ipapplication')),
                ('assigned_evaluator', models.ForeignKey(blank=True, db_column='assigned_evaluator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('taken_by', models.ForeignKey(blank=True, db_column='taken_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case',
                'ordering': ('deadline', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ActivityTimeline',
            fields=[
                ('id', models.BigAutoField(db_column='timeline_id', primary_key=True, serialize=False)),
                ('role_visibility', models.CharField(choices=[('applicant', 'Applicant'), ('admin', 'Admin'), ('all', 'All')], max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('applicant_message', models.TextField(blank=True)),
                ('admin_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, db_column='performed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity_timeline', to='cases.case')),
            ],
            options={
                'db_table': 'activity_timeline',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='cases.case')),
                ('evaluator', models.ForeignKey(db_column='evaluator_id', on_delete=django.db.models.deletion.PROTECT, related_name='case_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_evaluation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(db_column='status_history_id', primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cases.case')),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_status_history',
                'ordering': ('-changed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='case_case_nu_3c14f4_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['applicant'], name='case_applica_f396a2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_evaluator'], name='case_assigne_b7decd_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['taken_by'], name='case_taken_b_a6301c_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='case_status_deb121_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['deadline'], name='case_deadlin_8e1017_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority_score'], name='case_priorit_fd53f3_idx'),
        ),
    ]
