# Generated by Django 5.2.1 on 2026-06-08 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimeline',
            name='case',
            field=models.ForeignKey(blank=True, db_column='case_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_timeline', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='caseevaluation',
            name='case',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='case',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='cases.case'),
        ),
        migrations.AlterUniqueTogether(
            name='caseevaluation',
            unique_together={('case', 'evaluator')},
        ),
        migrations.AddIndex(
            model_name='activitytimeline',
            index=models.Index(fields=['case', 'role_visibility'], name='activity_ti_case_id_ad9f41_idx'),
        ),
        migrations.AddIndex(
            model_name='casestatushistory',
            index=models.Index(fields=['case', '-changed_at'], name='case_status_case_id_0993f6_idx'),
        ),
    ]
