# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(db_column='log_id', primary_key=True, serialize=False)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(max_length=150)),
                ('target', models.CharField(blank=True, max_length=150)),
                ('record_id', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('log_timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_case', models.ForeignKey(blank=True, db_column='case_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.case')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ('-log_timestamp',),
                'indexes': [models.Index(fields=['log_timestamp'], name='audit_log_log_tim_33ab23_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'), models.Index(fields=['role'], name='audit_log_role_186789_idx'), models.Index(fields=['related_case'], name='audit_log_case_id_6ecb42_idx'), models.Index(fields=['record_id'], name='audit_log_record__a10a3a_idx')],
            },
        ),
    ]
