# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('cases', '0001_initial'),
        ('security_keys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRecord',
            fields=[
                ('id', models.BigAutoField(db_column='record_id', primary_key=True, serialize=False)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.PROTECT, related_name='ip_records', to='applications.ipapplication')),
                ('case', models.OneToOneField(db_column='case_id', on_delete=django.db.models.deletion.PROTECT, related_name='ip_record', to='cases.case')),
                ('encryption_key', models.ForeignKey(blank=True, db_column='encryption_key_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_records', to='security_keys.encryptionkey')),
            ],
            options={
                'db_table': 'ip_record',
                'ordering': ('-certification_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(db_column='listing_id', primary_key=True, serialize=False)),
                ('listing_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('ip_type', models.CharField(max_length=30)),
                ('inventor_name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('category', models.CharField(max_length=150)),
                ('availability_status', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.PROTECT, related_name='market_listings', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.PROTECT, related_name='market_listings', to='marketplace.iprecord')),
            ],
            options={
                'db_table': 'market_listing',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(db_column='bookmark_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='marketplace.marketlisting')),
            ],
            options={
                'db_table': 'bookmark',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='iprecord',
            index=models.Index(fields=['case'], name='ip_record_case_id_dbcd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='iprecord',
            index=models.Index(fields=['application'], name='ip_record_applica_21607c_idx'),
        ),
        migrations.AddIndex(
            model_name='iprecord',
            index=models.Index(fields=['is_certified'], name='ip_record_is_cert_ddab6b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['listing_code'], name='market_list_listing_6810cb_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['record'], name='market_list_record__4b99b6_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['admin'], name='market_list_admin_i_c57302_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['ip_type'], name='market_list_ip_type_41f254_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['status', 'is_active'], name='market_list_status_c8c1b6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['applicant'], name='bookmark_applica_a01571_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['listing'], name='bookmark_listing_bee8bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('applicant', 'listing'), name='unique_applicant_market_listing_bookmark'),
        ),
    ]
