# Generated by Django 4.2.30 on 2026-05-01 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketplaceitem',
            name='marketplace_is_publ_148de3_idx',
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='marketplaceitem',
            index=models.Index(fields=['is_public', 'is_archived', '-created_at'], name='marketplace_is_publ_560583_idx'),
        ),
    ]
