# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(db_column='key_id', primary_key=True, serialize=False)),
                ('key_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('key_name', models.CharField(max_length=150)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('rotated', 'Rotated'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('encrypted_key_material', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('rotation_policy', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_backup', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_encryption_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encryption_key',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KeyActivityLog',
            fields=[
                ('id', models.BigAutoField(db_column='key_activity_id', primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(db_column='key_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='security_keys.encryptionkey')),
                ('performed_by', models.ForeignKey(blank=True, db_column='performed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'key_activity_log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='encryptionkey',
            index=models.Index(fields=['key_code'], name='encryption__key_cod_76a822_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptionkey',
            index=models.Index(fields=['status'], name='encryption__status_4fdfda_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptionkey',
            index=models.Index(fields=['is_primary'], name='encryption__is_prim_35df32_idx'),
        ),
    ]
