# Generated by Django 5.2.1 on 2026-06-08 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_keys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='keyactivitylog',
            index=models.Index(fields=['key'], name='key_activit_key_id_185926_idx'),
        ),
        migrations.AddIndex(
            model_name='keyactivitylog',
            index=models.Index(fields=['created_at'], name='key_activit_created_88ab91_idx'),
        ),
        migrations.AddConstraint(
            model_name='encryptionkey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='unique_active_primary_key'),
        ),
    ]
