# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('evaluator', 'Evaluator'), ('admin', 'Admin')], default='applicant', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('locked', 'Locked'), ('archived', 'Archived')], default='active', max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(db_column='applicant_profile_id', primary_key=True, serialize=False)),
                ('applicant_type', models.CharField(choices=[('faculty', 'Faculty'), ('staff', 'Staff'), ('student', 'Student'), ('external', 'External')], max_length=30)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('student_or_employee_id', models.CharField(blank=True, max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/applicants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applicant_profile',
            },
        ),
        migrations.CreateModel(
            name='EvaluatorProfile',
            fields=[
                ('id', models.BigAutoField(db_column='evaluator_profile_id', primary_key=True, serialize=False)),
                ('specialization', models.CharField(choices=[('patent_mechanical', 'Patent - Mechanical'), ('patent_electrical', 'Patent - Electrical'), ('utility_model', 'Utility Model'), ('industrial_design', 'Industrial Design'), ('trademark', 'Trademark'), ('copyright', 'Copyright')], max_length=40)),
                ('workload_count', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evaluator_profile',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(db_column='otp_id', primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('registration', 'Registration'), ('password_reset', 'Password Reset')], max_length=30)),
                ('otp_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_code',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_3744fd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='user_status_116710_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'purpose', 'created_at'], name='otp_code_user_id_8922b8_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['expires_at'], name='otp_code_expires_8d1cde_idx'),
        ),
    ]
