-- 002_tables.sql
-- CREATE TABLE statements for the current Django database schema.
--
-- Notes:
-- - Primary keys follow the current project strategy: BigAutoField/bigint
--   identity for project models, AutoField/integer identity for relevant
--   Django contrib tables.
-- - Django model defaults such as auto_now_add, auto_now, and CharField
--   defaults are application-level defaults in the migrations. They are not
--   added as PostgreSQL column defaults here.
-- - Foreign keys, unique constraints, check constraints, and indexes are added
--   in 003_indexes_and_constraints.sql.

CREATE TABLE IF NOT EXISTS public.django_content_type (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label varchar(100) NOT NULL,
    model varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.auth_permission (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.auth_group (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.django_session (
    session_key varchar(40) PRIMARY KEY,
    session_data text NOT NULL,
    expire_date timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public."user" (
    password varchar(128) NOT NULL,
    last_login timestamptz NULL,
    is_superuser boolean NOT NULL,
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    username varchar(150) NULL,
    first_name varchar(150) NOT NULL,
    middle_name varchar(150) NOT NULL,
    last_name varchar(150) NOT NULL,
    role varchar(20) NOT NULL,
    status varchar(20) NOT NULL,
    contact_number varchar(30) NOT NULL,
    address text NOT NULL,
    is_staff boolean NOT NULL,
    failed_login_attempts smallint NOT NULL,
    locked_until timestamptz NULL,
    last_login_ip inet NULL,
    last_login_at timestamptz NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_user_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.django_admin_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_time timestamptz NOT NULL,
    object_id text NULL,
    object_repr varchar(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer NULL,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.token_blacklist_outstandingtoken (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NULL,
    jti varchar(255) NOT NULL,
    token text NOT NULL,
    created_at timestamptz NULL,
    expires_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.token_blacklist_blacklistedtoken (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id bigint NOT NULL,
    blacklisted_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.applicant_profile (
    applicant_profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    applicant_type varchar(30) NOT NULL,
    institution varchar(255) NOT NULL,
    student_or_employee_id varchar(100) NOT NULL,
    profile_photo varchar(100) NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.evaluator_profile (
    evaluator_profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    specialization varchar(40) NOT NULL,
    workload_count integer NOT NULL,
    is_available boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.otp_code (
    otp_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    purpose varchar(30) NOT NULL,
    otp_hash varchar(255) NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at timestamptz NULL,
    attempts smallint NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.encryption_key (
    key_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_code varchar(50) NOT NULL,
    key_name varchar(150) NOT NULL,
    algorithm varchar(50) NOT NULL,
    status varchar(20) NOT NULL,
    encrypted_key_material text NOT NULL,
    created_by_id bigint NULL,
    created_at timestamptz NOT NULL,
    rotated_at timestamptz NULL,
    disabled_at timestamptz NULL,
    rotation_policy varchar(255) NOT NULL,
    is_primary boolean NOT NULL,
    is_backup boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS public.ip_application (
    application_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_code varchar(40) NOT NULL,
    applicant_id bigint NOT NULL,
    ip_type varchar(30) NOT NULL,
    title varchar(255) NOT NULL,
    description text NOT NULL,
    abstract text NOT NULL,
    claims text NOT NULL,
    technical_explanation text NOT NULL,
    novelty_explanation text NOT NULL,
    supporting_details text NOT NULL,
    declaration_accepted boolean NOT NULL,
    status varchar(20) NOT NULL,
    completeness_score smallint NOT NULL,
    language_validation_status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL,
    submitted_at timestamptz NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.application_checklist (
    checklist_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    item_name varchar(255) NOT NULL,
    status varchar(20) NOT NULL,
    remarks text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public."case" (
    case_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_number varchar(40) NOT NULL,
    application_id bigint NOT NULL,
    applicant_id bigint NOT NULL,
    assigned_evaluator_id bigint NULL,
    taken_by_id bigint NULL,
    is_taken boolean NOT NULL,
    taken_at timestamptz NULL,
    status varchar(30) NOT NULL,
    priority_score integer NOT NULL,
    priority_label varchar(20) NOT NULL,
    deadline timestamptz NULL,
    sla_stage varchar(100) NOT NULL,
    sla_due_date timestamptz NULL,
    evaluation_summary text NOT NULL,
    evaluator_recommendation text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.case_status_history (
    status_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    previous_status varchar(30) NOT NULL,
    new_status varchar(30) NOT NULL,
    changed_by_id bigint NULL,
    remarks text NOT NULL,
    changed_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.activity_timeline (
    timeline_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    performed_by_id bigint NULL,
    role_visibility varchar(20) NOT NULL,
    action varchar(255) NOT NULL,
    applicant_message text NOT NULL,
    admin_message text NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.case_evaluation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    evaluator_id bigint NOT NULL,
    content text NOT NULL,
    recommendation text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.document (
    document_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    uploaded_by_id bigint NOT NULL,
    document_type varchar(100) NOT NULL,
    original_filename varchar(255) NOT NULL,
    encrypted_file_path varchar(100) NOT NULL,
    file_size bigint NOT NULL,
    mime_type varchar(150) NOT NULL,
    encryption_key_id bigint NOT NULL,
    nonce varchar(50) NOT NULL,
    checksum varchar(64) NOT NULL,
    uploaded_at timestamptz NOT NULL,
    is_confidential boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS public.fee_assessment (
    assessment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    application_id bigint NOT NULL,
    evaluator_id bigint NULL,
    amount numeric(12, 2) NOT NULL,
    fee_type varchar(120) NOT NULL,
    description text NOT NULL,
    status varchar(20) NOT NULL,
    issued_at timestamptz NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.payment (
    payment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id bigint NOT NULL,
    case_id bigint NOT NULL,
    applicant_id bigint NOT NULL,
    amount_paid numeric(12, 2) NOT NULL,
    payment_method varchar(80) NOT NULL,
    receipt_no varchar(100) NOT NULL,
    encrypted_receipt_file varchar(100) NOT NULL,
    original_filename varchar(255) NOT NULL,
    file_size bigint NOT NULL,
    mime_type varchar(150) NOT NULL,
    encryption_key_id bigint NOT NULL,
    nonce varchar(50) NOT NULL,
    checksum varchar(64) NOT NULL,
    payment_status varchar(20) NOT NULL,
    payment_date date NULL,
    verified_by_id bigint NULL,
    verified_at timestamptz NULL,
    remarks text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.conversation (
    conversation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    applicant_id bigint NOT NULL,
    evaluator_id bigint NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.message (
    message_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    content text NOT NULL,
    sent_at timestamptz NOT NULL,
    is_read boolean NOT NULL,
    has_attachment boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS public.message_attachment (
    attachment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint NOT NULL,
    file_path varchar(100) NOT NULL,
    original_filename varchar(255) NOT NULL,
    file_size bigint NOT NULL,
    mime_type varchar(150) NOT NULL,
    uploaded_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notification (
    notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    related_case_id bigint NULL,
    type varchar(100) NOT NULL,
    title varchar(255) NOT NULL,
    content text NOT NULL,
    role_visibility varchar(30) NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.audit_log (
    log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NULL,
    case_id bigint NULL,
    account_name varchar(255) NOT NULL,
    role varchar(30) NOT NULL,
    action varchar(150) NOT NULL,
    target varchar(150) NOT NULL,
    record_id varchar(100) NOT NULL,
    details text NOT NULL,
    ip_address inet NULL,
    user_agent text NOT NULL,
    log_timestamp timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.ip_record (
    record_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    application_id bigint NOT NULL,
    encryption_key_id bigint NULL,
    certification_date date NULL,
    is_certified boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.market_listing (
    listing_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_code varchar(50) NOT NULL,
    record_id bigint NOT NULL,
    admin_id bigint NOT NULL,
    title varchar(255) NOT NULL,
    ip_type varchar(30) NOT NULL,
    inventor_name varchar(255) NOT NULL,
    short_description text NOT NULL,
    full_description text NOT NULL,
    category varchar(150) NOT NULL,
    availability_status varchar(100) NOT NULL,
    image varchar(100) NULL,
    status varchar(20) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.bookmark (
    bookmark_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id bigint NOT NULL,
    listing_id bigint NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.inquiry (
    inquiry_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_code varchar(50) NOT NULL,
    user_id bigint NULL,
    listing_id bigint NULL,
    sender_name varchar(255) NOT NULL,
    email varchar(254) NOT NULL,
    category varchar(100) NOT NULL,
    subject varchar(255) NOT NULL,
    message text NOT NULL,
    popularity_count integer NOT NULL,
    status varchar(20) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.announcement (
    announcement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id bigint NOT NULL,
    title varchar(255) NOT NULL,
    content text NOT NULL,
    category varchar(120) NOT NULL,
    is_published boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.report_export (
    report_export_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generated_by_id bigint NOT NULL,
    report_type varchar(120) NOT NULL,
    file_path varchar(100) NULL,
    created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.key_activity_log (
    key_activity_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id bigint NOT NULL,
    action varchar(100) NOT NULL,
    performed_by_id bigint NULL,
    details text NOT NULL,
    ip_address inet NULL,
    created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.ipophl_email_parse (
    email_parse_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender varchar(254) NOT NULL,
    subject varchar(255) NOT NULL,
    body text NOT NULL,
    case_number_detected varchar(80) NOT NULL,
    report_type varchar(150) NOT NULL,
    deadline_detected date NULL,
    required_action text NOT NULL,
    attachments_metadata jsonb NOT NULL,
    matched_case_id bigint NULL,
    status varchar(20) NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.nlq_query (
    nlq_query_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NULL,
    raw_query text NOT NULL,
    detected_intent varchar(150) NOT NULL,
    extracted_filters jsonb NOT NULL,
    result_count integer NOT NULL,
    created_at timestamptz NOT NULL
);
