# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(db_column='report_export_id', primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=120)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(db_column='generated_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_export',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['generated_by'], name='report_expo_generat_42e2ef_idx'), models.Index(fields=['report_type'], name='report_expo_report__a427c4_idx'), models.Index(fields=['created_at'], name='report_expo_created_5b869b_idx')],
            },
        ),
    ]
