# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('security_keys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(db_column='document_id', primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_file_path', models.FileField(upload_to='encrypted/documents/')),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=150)),
                ('nonce', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('encryption_key', models.ForeignKey(db_column='encryption_key_id', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='security_keys.encryptionkey')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document',
                'ordering': ('-uploaded_at',),
                'indexes': [models.Index(fields=['case'], name='document_case_id_f867da_idx'), models.Index(fields=['uploaded_by'], name='document_uploade_523401_idx'), models.Index(fields=['document_type'], name='document_documen_eae0b0_idx'), models.Index(fields=['uploaded_at'], name='document_uploade_7afb96_idx')],
            },
        ),
    ]
