# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(db_column='conversation_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.PROTECT, related_name='applicant_conversations', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='cases.case')),
                ('evaluator', models.ForeignKey(db_column='evaluator_id', on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(db_column='message_id', primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('has_attachment', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
                'ordering': ('sent_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(db_column='attachment_id', primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to='messages/attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
            ],
            options={
                'db_table': 'message_attachment',
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('case', 'applicant', 'evaluator'), name='unique_case_applicant_evaluator_conversation'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='message_convers_34c8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='message_sender__0e912c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='message_is_read_8eefe1_idx'),
        ),
    ]
