# Generated by Django 5.2.1 on 2026-06-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_activitytimeline_case_and_more'),
        ('messaging', '0001_initial'),
        ('security_keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='encryption_key',
            field=models.ForeignKey(blank=True, db_column='encryption_key_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_attachments', to='security_keys.encryptionkey'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='nonce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='case',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='cases.case'),
        ),
    ]
