# Generated by Django 4.2.30 on 2026-05-01 14:41

import core.utils.file_validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0003_iprequirement_paymentrecord_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=core.utils.file_validators.generate_upload_path, validators=[core.utils.file_validators.validate_file_extension, core.utils.file_validators.validate_file_size])),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='applications.ipapplication')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['application', 'created_at'], name='workflow_ca_applica_42711f_idx'), models.Index(fields=['sender', '-created_at'], name='workflow_ca_sender__2e7253_idx'), models.Index(fields=['is_read'], name='workflow_ca_is_read_1296b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('alert', 'Alert'), ('system', 'System')], default='news', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='workflow_an_categor_55302e_idx'), models.Index(fields=['is_published', '-created_at'], name='workflow_an_is_publ_efb201_idx')],
            },
        ),
    ]
