# Generated by Django 5.2.1 on 2026-05-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(db_column='notification_id', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(blank=True, db_column='type', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('role_visibility', models.CharField(blank=True, max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, db_column='related_case_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='cases.case')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient'], name='notificatio_user_id_3cbd6f_idx'), models.Index(fields=['related_case'], name='notificatio_related_2c0ef0_idx'), models.Index(fields=['notification_type'], name='notificatio_type_f65c28_idx'), models.Index(fields=['role_visibility'], name='notificatio_role_vi_3fceb9_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_8a483f_idx')],
            },
        ),
    ]
